apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-robot
  namespace: pvc-llama
subjects:
- kind: ServiceAccount
  name: job-robot # Name of the ServiceAccount
  namespace: pvc-llama
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: job-robot # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io